#!/bin/bash
RED='\033[0;31m'
GRN='\033[0;32m'
NC='\033[0m'
if [[ -z $1 ]]; then
	echo -e "[NEMESIS] ${RED}Error:${NC} No command given.${NC}"
	exit 1
fi
if [[ $1 == "unload" ]]; then
	echo -e "[NEMESIS] Rewriting Library..."
    sudo mv /Library/Application\ Support/LanSchool /Library/Application\ Support/Nemesis_protected_LanSchool
	EXITCODE=$(echo $?)
	echo -e "[NEMESIS] ${GRN}Done.${NC} Exiting launchctlmgr...${NC}"
	exit $EXITCODE
elif [[ $1 == "load" ]]; then
	echo -e "[NEMESIS] Rewriting Library..."
    sudo mv /Library/Application\ Support/Nemesis_protected_LanSchool /Library/Application\ Support/LanSchool
	EXITCODE=$(echo $?)
	echo -e "[NEMESIS] ${GRN}Done.${NC} Exiting launchctlmgr...${NC}"
	exit $EXITCODE
else
	echo -e "[NEMESIS] ${RED}Error:${NC} No such command.${NC}"
	exit 2
fi
