#!/bin/bash
RED='\033[0;31m'
GRN='\033[0;32m'
NC='\033[0m'
if [[ -z "$1" ]]; then
	echo -e "${RED}Error:${NC} Passcode is empty."
	exit 1
elif [[ -z "$2" ]]; then
	echo -e "${RED}Error:${NC} Path is empty."
	exit 1
elif [[ ! -f "$2" ]]; then
	echo -e "${RED}Error:${NC} No such file."
	exit 1
else
	PASS=$(commoncrypto hash sha512 "$1")
	echo -n "$PASS" | hdiutil attach "$2" -stdinpass >/dev/null
	EXITCODE=$?
fi
exit $EXITCODE